---

- name: Deploy Seed
  hosts:
  - tag_Name_reducto-seed-01
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      
      - name: Kill previous run
        command: killall java
        ignore_errors: yes
        
      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Seed Akka
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.SeedDaemon &
        async: 450000
        poll: 0