---

- name: Kill-Dist
  hosts:
  - tag_Name_reducto-frontend-01
  - tag_Name_reducto-backend-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous run
        command: killall java
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/


- name: Re-deploy Frontend
  hosts:
  - tag_Name_reducto-frontend-01
  
  user: ubuntu
  sudo: true
  gather_facts: false

  tasks:
    - name: Run Frontend
      command: nohup /usr/local/reducto-dist/bin/start com.winston.api.ApiBoot &
      async: 450000
      poll: 0


- name: Re-deploy Backend
  hosts:
  - tag_Name_reducto-backend-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Run Backend 1
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 2
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 3
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 4
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

