---

- name: Send distribution
  hosts:
  - tag_Name_reducto-frontend-01
  - tag_Name_reducto-worker-01
  - tag_Name_reducto-supervisor-01
  - tag_Name_reducto-parser-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/


- name: Re-deploy Frontend
  hosts:
  - tag_Name_reducto-frontend-01
  
  user: ubuntu
  sudo: true
  gather_facts: false

  tasks:
      - name: Kill previous run
        command: stop reducto-frontend N=1
        ignore_errors: yes

      - name: Run frontend daemon
        command: start reducto-frontend N=1


- name: Re-deploy Worker
  hosts:
  - tag_Name_reducto-worker-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous worker runs
        command: stop reducto-worker N={{ item }}
        with_items:
           - 1
           - 2
        ignore_errors: yes

      - name: Run worker daemons
        command: start reducto-worker N={{ item }}
        with_items:
           - 1
           - 2

      - name: Kill previous parser runs
        command: stop reducto-parser N={{ item }}
        with_items:
           - 1
           - 2
           - 3
           - 4
        ignore_errors: yes

      - name: Run parser daemons
        command: start reducto-parser N={{ item }}
        with_items:
           - 1
           - 2
           - 3
           - 4

- name: Re-deploy Parser
  hosts:
  - tag_Name_reducto-parser-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous parser runs
        command: stop reducto-parser N={{ item }}
        with_items:
           - 1
           - 2
           - 3
           - 4
        ignore_errors: yes

      - name: Run parser daemons
        command: start reducto-parser N={{ item }}
        with_items:
           - 1
           - 2
           - 3
           - 4


- name: Re-deploy Supervisor
  hosts:
  - tag_Name_reducto-supervisor-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous supervisor runs
        command: stop reducto-supervisor N=1

        ignore_errors: yes

      - name: Run supervisor daemons
        command: start reducto-supervisor N=1
