- name: Launch Backend Instances   
  hosts: local 
  connection: local
  user: root
  gather_facts: false

  vars:
    keypair: Akka
    security_group: Akka

    instance_name: Reducto-Backend-01

    # Instace types
    instance_type: m1.large

    # Image (Ubuntu 12.04)
    image: ami-a73264ce 

    # Instance Counts
    instance_count: 1

    # Region
    region: us-east-1

  user: ubuntu
  tasks:
 
    # Instance
    - name: Launch Backend instances
      local_action: ec2 keypair={{keypair}} group={{security_group}} instance_type={{instance_type}} image={{image}} wait=true count={{instance_count}} region={{region}} instance_tags='{"Name":"{{instance_name}}"}'
      register: ec2

    - name: Add all worker instance public IPs to host group
      local_action: add_host hostname={{item.public_ip}} groupname=launched ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/{{keypair}}.pem
      with_items: ec2.instances

    - name: Create volumes and attach
      local_action: ec2_vol instance={{item.id}} volume_size=8 region={{region}} device_name=xvdf
      with_items: ec2.instances
      register: ec2_vol
    
    - name: Wait for ssh to come up
      local_action: wait_for host={{item.public_dns_name}} port=22 timeout=320 state=started
      with_items: ec2.instances

- name: Install and Prepare 
  hosts: launched 
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
      - common
      - java
      - upstart
